<div class="container">
    <div class="login-page">
        <div class="form">
            <div class="">
                <h3 class="panel-title"><?php echo $this->getPageTitle() ?></h3>
            </div>
            <form class="login-form" action="/user/store" method="post" accept-charset="utf-8">
                <input type="text" name="name"
                    <?php if(isset($this->inputs['name']) && !empty($this->inputs['name'])){
                        echo 'value="' . $this->inputs['name'] . '"';
                    } else {
                        echo 'placeholder="name"';
                    } ?>
                />
                <?php if ($this->errors['name']): ?>
                    <span class="help-block"><?php echo $this->errors['name'] ?></span>
                <?php endif; ?>
                <input type="text" name="email"
                    <?php if(isset($this->inputs['email']) && !empty($this->inputs['email'])){
                        echo 'value="' . $this->inputs['email'] . '"';
                    } else {
                        echo 'placeholder="email"';
                    } ?>
                />
                <?php if ($this->errors['email']): ?>
                    <span class="help-block"><?php echo $this->errors['email'] ?></span>
                <?php endif; ?>
                <input type="password" name="password" placeholder="password" />

                <?php if ($this->errors['password']): ?>
                    <span class="help-block"><?php echo $this->errors['password'] ?></span>
                <?php endif; ?>
                <button type="submit" class="btn">Save</button>
            </form>
        </div>
    </div>
</div>
