<div class="">
    <div class="">
        <h1><?php echo $this->view->nome ?></h1>
    </div>
    <div class="posts">
        <form action="store" method="post" accept-charset="utf-8">
            <div class="form">
                <label for="title">Title</label>
                <input type="text" name="title" class="form-item">
            </div>
            <div class="form">
                <label for="content">Content</label>
                <textarea name="content" class="form-item" rows="10"></textarea>
            </div>
            <a href="/posts"><button type="button" class="btn float-left">Cancel</button></a>
            <button type="submit" class="btn float-left">Save</button>
        </form>
    </div>
</div>

