<div class="container">
    <div class="">
        <h1><?php echo $this->getPageTitle(); ?></h1>
    </div>
    <form action="store" method="post" accept-charset="utf-8">
        <div class="posts">
            <div class="form">
                <label for="title">Title</label>
                <input type="text" name="title"
                       class="form-item <?php echo (isset($this->errors['title'])) ? "required-invalid" : "valid";?>"
                       value="<?php echo (isset($this->inputs['title'])) ? $this->inputs['title'] : $this->view->post->title;?>">
                <?php if($this->errors['title']) { ?>
                <span class="help-block"><?php echo $this->errors['title']; }?></span>
            </div>
            <div class="form">
                <label for="content">Content</label>
                <textarea name="content" class="form-item <?php echo (isset($this->errors['content'])) ? "required-invalid" : "valid";?>" rows="10"><?php echo (isset($this->inputs['content'])) ? $this->inputs['content'] : $this->view->post->content;?></textarea>
                <?php if($this->errors['content']) : ?>
                    <span class="help-block"><?php echo $this->errors['content'];?></span>
                <?php endif; ?>
            </div>
            <a href="/posts"><button type="button" class="btn float-left">Cancel</button></a>
            <button type="submit" class="btn float-left">Save</button>
        </div>
        <div class="category">
            <div class="form">
                <label for="title">Categories</label>
                <?php foreach ($this->view->categories as $cat) : ?>
                    <div class="checkbox">
                        <input type="checkbox" name="category_id[]" value="<?php echo $cat->id ?>"
                            <?php foreach($this->view->post->category as $item) {
                                echo ($cat->id == $item->id) ? 'checked' : '';
                            }?>
                        />
                        <?php echo $cat->name ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </form>
</div>
