<div class="">
    <div class="">
        <h1>Posts</h1>
        <p><?php echo $this->view->nome ?></p>
    </div>
    <div class="posts">
        <?php foreach($this->view->posts as $post){ ?>
            <ul >
                <li>
                    <h3 class="">
                        <a href="/post/<?php echo $post->id; ?>/show"><?php echo $post->title ?> </a>
                    </h3>
                    <p><?php echo $post->content ?> </p>
                </li>
            </ul>

        <?php } ?>
    </div>
</div>

