<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="/assets/css/style.css">
    <title>Home | My First Framework</title>
</head>
<body>
    <?php require_once (__DIR__ . "/menu.phtml"); ?>
    <h1>Page not found</h1>
    <div>
        <p>Powered by: Kylb</p>
    </div>

    <!--<script src="/assets/js/jquery-3.2.1.slim.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>-->
</body>
</html>