<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="/assets/css/style.css">
    <title><?php echo $this->getPageTitle("|"); ?>KylbFW</title>
</head>
<body>
    <?php require_once (__DIR__ . "/menu.phtml"); ?>
    <p><?php $this->content();?></p>
    <footer>
        <p>
            Kylb Kwnia - 2018 - Copyleft
        </p>
    </footer>
</body>
</html>