<nav>
    <header>
        <a href="https://kylb.github.io/"><img class="logo" src="/assets/img/kyubi.png" alt="Logomarca Kyubi"></a>
        <label for="menu-resp" class="menu-resp">Menu</label>
        <input type="checkbox" id="menu-resp" role="button">
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/posts">Posts</a></li>
            <li><a href="https://kylb.github.io/">Github.io</a></li>
        </ul>
    </header>
</nav>