<nav>
    <header>
        <a href="https://kylb.github.io/"><img class="logo float-left" src="/assets/img/kyubi.png" alt="Logomarca Kyubi"></a>
        <label for="menu-resp" class="menu-resp">Menu</label>
        <input type="checkbox" id="menu-resp" role="button">
        <ul class="float-left">
            <li><a href="/">Home</a></li>
            <li><a href="/posts">Posts</a></li>
        </ul>
        <ul class="float-right">
            <?php if($this->auth->check()){?>
                <li><a href="/logout">Logout</a></li>
            <?php } else { ?>
                <li><a href="/login">Login</a></li>
                <li><a href="/user/create">Register</a></li>
            <?php } ?>
        </ul>
    </header>
</nav>